In [1]:
import numpy as np

Задача 1

In [5]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


Задача 2

In [18]:
Z = np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Задача 3

In [21]:
A = np.random.randint(1, 10, size=(5, 5))
print(A)

[[4 7 8 3 4]
 [3 6 6 9 6]
 [8 6 7 4 4]
 [3 1 7 1 2]
 [9 6 4 3 5]]


Задача 4

In [20]:
B = np.random.rand(4, 4)
print(B)

[[0.63881089 0.06102598 0.71999115 0.11007842]
 [0.72707245 0.71585973 0.34417363 0.61191142]
 [0.56044909 0.49864198 0.83211255 0.51012218]
 [0.38320945 0.48604225 0.20090264 0.39471142]]


Задача 5

In [22]:
A_1 = np.random.randint(1, 10, size=(5))
B_1 = np.random.randint(1, 10, size=(5))
print(f'sum = {A_1 + B_1}, dif = {A_1 - B_1}, mul = {A_1 * B_1}')

sum = [ 7 18 10 10  8], dif = [ 1  0  2  6 -6], mul = [12 81 24 16  7]


Задача 6

In [27]:
v_1 = np.random.rand(7)*100
v_2 = np.random.rand(7)*100
print(np.multiply(v_1, v_2))

[1378.47565253 6113.12037893 4582.4226031  2019.99547133 1797.15740468
  529.0425177  2592.44597062]


Задача 7

In [31]:
M_1 = np.random.randint(1, 11, size=(2, 2))
M_2 = np.random.randint(1, 11, size=(2, 3))
RES_M = np.dot(M_1, M_2)
print(RES_M)

[[76 49 86]
 [43 32 48]]


Задача 8

In [37]:
N = np.random.randint(1, 11, size=(3, 3))
if np.linalg.det(N) != 0:
  N_INV = np.linalg.inv(N)
  print(N_INV)
else:
  print('Матриця не оборотна')

[[-2.          1.          1.        ]
 [ 9.16666667 -4.66666667 -4.        ]
 [-2.33333333  1.33333333  1.        ]]


Задача 9

In [38]:
L = (np.matrix(np.random.rand(4, 4))).T
print(L)

[[0.68163574 0.15631408 0.4249185  0.43484319]
 [0.82380194 0.35328466 0.6198261  0.69214642]
 [0.78298477 0.82073543 0.14672987 0.47850287]
 [0.05883486 0.37029634 0.60154792 0.63024691]]


Задача 10

In [40]:
a = np.random.randint(1, 11, 4)
A = np.random.randint(1, 11, size=(3, 4))
result = np.dot(A, a)
print(result)

[46 64 55]


Задача 11

In [43]:
B = np.random.rand(2, 3)
b = np.random.rand(3)
result = np.dot(B, b)
print(result)

[0.86701888 0.50165771]


Задача 12

In [44]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
mul = x * y
print(mul)

[[12  6]
 [ 9 32]]


Задача 13

In [45]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
mul = np.dot(x, y)
print(mul)

[[26 26]
 [82 82]]


Задача 14

In [46]:
Z = np.sum(np.random.randint(1, 101, size=(5, 5)))
print(Z)

1366


Задача 15

In [49]:
K = np.random.randint(1, 11, size=(4, 4))
C = np.random.randint(1, 11, size=(4, 4))
print(K - C)

[[-7  7 -2  2]
 [ 2  2 -4 -3]
 [ 5 -2  3 -3]
 [-1 -4  0 -1]]


Задача 16

In [68]:
W = np.random.rand(3, 3)
my_vector = np.array([np.sum(W[0][:2]), np.sum(W[1][:2]), np.sum(W[2][:2])])
column_vector = my_vector[:, np.newaxis]
print(column_vector)

[0.43437967 1.29257156 1.33458379]
[[0.43437967]
 [1.29257156]
 [1.33458379]]


Задача 17

In [77]:
Y = np.random.randint(1, 50, size=(3, 4))
print(Y * Y)

[[1936  484 1444 1681]
 [1225 1024  144  784]
 [1024   49   64   64]]


Задача 18

In [80]:
vector_first = np.random.randint(1, 50, 4)
vector_second = np.sqrt(vector_first )
print(vector_first)
print(vector_second)

[11 42 24 47]
[3.31662479 6.4807407  4.89897949 6.8556546 ]
